import type { ServiceDefinition } from './service-detection.types';

// Valores por defecto cuando no se puede identificar un servicio concreto.
export const GENERIC_ICON_NAME = 'generic';
export const GENERIC_SERVICE_ID = 'generic';

// Iniciales mostradas cuando un servicio no tiene SVG dedicado.
export const SERVICE_ICON_GLYPHS: Record<string, string> = {
  generic: '*',
  steam: 'S',
  steamcommunity: 'SC',
  github: 'G',
  gitlab: 'GL',
  google: 'Go',
  gmail: 'GM',
  youtube: 'YT',
  vimeo: 'Vi',
  discord: 'D',
  reddit: 'R',
  stackoverflow: 'SO',
  wikipedia: 'Wi',
  imgur: 'Im',
  twitch: 'Tw',
  amazon: 'A',
  paypal: 'P',
  binance: 'B',
  twitterx: 'X',
  tumblr: 'Tu',
  facebook: 'F',
  messenger: 'Ms',
  instagram: 'IG',
  linkedin: 'IN',
  microsoft: 'MS',
  windows: 'Win',
  visualstudio: 'VS',
  visualstudiocode: 'VSC',
  outlook: 'OL',
  dropbox: 'DB',
  wetransfer: 'WT',
  mega: 'M',
  notion: 'N',
  openai: 'OA',
  chatgpt: 'CG',
  riotgames: 'RG',
  epicgames: 'EG',
  ubisoft: 'U',
  uber: 'Ub',
  udemy: 'Ud',
  ea: 'EA',
  spotify: 'Sp',
  soundcloud: 'SC',
  strava: 'Stv',
  netflix: 'Nf',
  disneyplus: 'D+',
  primevideo: 'PV',
  crunchyroll: 'Cr',
  apple: 'Ap',
  icloud: 'IC',
  jira: 'Ji',
  confluence: 'Co',
  trello: 'Tr',
  bitbucket: 'BB',
  gitkraken: 'GK',
  atlassian: 'At',
  figma: 'Fi',
  zoom: 'Zm',
  loom: 'Lo',
  nasa: 'NA',
  telegram: 'Tg',
  wechat: 'WC',
  weibo: 'WB',
  tencent: 'Tc',
  whatsapp: 'Wa',
  protonmail: 'PM',
  postman: 'Po',
  tiktok: 'TT',
  tinder: 'Ti',
  pinterest: 'Pn',
  onlyfans: 'OF',
  roblox: 'Rb',
  battlenet: 'BN',
  playstation: 'Ps',
  playstore: 'PS',
  docker: 'Do',
  php: 'Ph',
  redhat: 'RH',
  chrome: 'Ch',
  firefox: 'Fx',
  opera: 'Op',
  brave: 'Br',
  onepassword: '1P',
  lastpass: 'LP',
  bitwarden: 'BW',
  coinbase: 'Cb',
  coinmarketcap: 'CMC',
  stripe: 'St',
  tripadvisor: 'TA',
  shopify: 'Sh',
  patreon: 'Pa',
  evernote: 'Ev',
  obsidian: 'Ob',
  linear: 'Li',
  vercel: 'Ve',
  webflow: 'Wf',
  webpack: 'Wp',
  wordpress: 'Wp',
  netlify: 'Ne',
  snapchat: 'Sc',
  skype: 'Sk',
  teams: 'Tm',
  adobe: 'Ad',
  yahoo: 'Ya',
  yahoomail: 'YM',
  sendgrid: 'SG',
  twilio: 'Tw',
  aws: 'AWS',
  cloudflare: 'CF',
  virustotal: 'VT',
  digitalocean: 'DO',
  vultr: 'Vu',
  heroku: 'He',
  railway: 'Rw',
  render: 'Re',
  supabase: 'Su',
  firebase: 'Fb',
  w3schools: 'W3',
  planetscale: 'PS',
  mongodb: 'Mg',
  mysql: 'My',
  postgresql: 'Pg',
  xbox: 'XB',
  nintendo: 'Ni',
  nvidia: 'Nv',
  rockstar: 'RS',
  genshin: 'Ge',
  minecraft: 'Mc',
  valorant: 'Va',
  kraken: 'Kr',
  etoro: 'eT',
  tradingview: 'TV',
  bbva: 'BB',
  santander: 'Sa',
  caixabank: 'Cx',
  bankinter: 'Bi',
  laboralkutxa: 'LK',
  sabadell: 'Sb',
  abanca: 'Ab',
  unicaja: 'Un',
  openbank: 'Obk',
  kutxabank: 'Kb',
  ibercaja: 'Ib',
  ingbank: 'ING',
  metamask: 'MM',
  trustwallet: 'TW',
  ledger: 'Le',
  revolut: 'Rv',
  wise: 'Wi',
  hbo: 'HBO',
  hbomax: 'HM',
  paramountplus: 'P+',
  appletv: 'TV',
  proton: 'Pr',
  zoho: 'Zo',
  fastmail: 'Fm',
  icloudmail: 'IM',
  onedrive: 'OD',
  googledrive: 'GD',
  box: 'Bx',
  anthropic: 'An',
  claude: 'Cl',
  perplexity: 'Px',
  midjourney: 'Mj',
  huggingface: 'HF',
  replicate: 'Rp',
  canva: 'Ca',
  monday: 'Mo',
  asana: 'As',
  clickup: 'Cu',
  todoist: 'To',
  airtable: 'Atb',
  adyen: 'AD',
  airbnb: 'AI',
  algolia: 'AL',
  aliexpress: 'AL',
  alipay: 'AL',
  amplitude: 'AM',
  android: 'AN',
  androidstudio: 'AN',
  angellist: 'AN',
  angular: 'AN',
  apollo: 'AP',
  appstore: 'AP',
  asanabusiness: 'AS',
  auth0: 'AU',
  autodesk: 'AU',
  azure: 'AZ',
  basecamp: 'BA',
  behance: 'BE',
  bigcommerce: 'BI',
  bing: 'BI',
  bitly: 'BI',
  blender: 'BL',
  bootstrap: 'BO',
  braintree: 'BR',
  bugsnag: 'BU',
  buzzfeed: 'BU',
  cashapp: 'CA',
  circleci: 'CI',
  clerk: 'CL',
  codecademy: 'CO',
  codepen: 'CO',
  codesandbox: 'CO',
  coursera: 'CO',
  crunchbase: 'CR',
  dailymotion: 'DA',
  datadog: 'DA',
  deezer: 'DE',
  deliveroo: 'DE',
  deno: 'DE',
  disqus: 'DI',
  dockerhub: 'DO',
  dribbble: 'DR',
  duckduckgo: 'DU',
  ebay: 'EB',
  elastic: 'EL',
  elasticsearch: 'EL',
  envato: 'EN',
  etsy: 'ET',
  eventbrite: 'EV',
  expo: 'EX',
  expressjs: 'EX',
  fastly: 'FA',
  feedly: 'FE',
  fiverr: 'FI',
  flyio: 'FL',
  forgejo: 'FO',
  formstack: 'FO',
  foursquare: 'FO',
  framer: 'FR',
  freshbooks: 'FR',
  frontapp: 'FR',
  gatsby: 'GA',
  ghost: 'GH',
  giphy: 'GI',
  gitea: 'GI',
  godaddy: 'GO',
  goodreads: 'GO',
  grafana: 'GR',
  grammarly: 'GR',
  gumroad: 'GU',
  hackernews: 'HA',
  hashnode: 'HA',
  homeassistant: 'HO',
  hotjar: 'HO',
  hubspot: 'HU',
  ifttt: 'IF',
  indeed: 'IN',
  invision: 'IN',
  jetbrains: 'JE',
  joomla: 'JO',
  jsdelivr: 'JS',
  kaggle: 'KA',
  kakao: 'KA',
  kickstarter: 'KI',
  klarna: 'KL',
  koa: 'KO',
  lastfm: 'LA',
  leetcode: 'LE',
  lemonsqueezy: 'LE',
  letterboxd: 'LE',
  liberapay: 'LI',
  linode: 'LI',
  mailchimp: 'MA',
  mailgun: 'MA',
  mapbox: 'MA',
  mattermost: 'MA',
  medium: 'ME',
  miro: 'MI',
  mixpanel: 'MI',
  mozilla: 'MO',
  namecheap: 'NA',
  nextcloud: 'NE',
  nextjs: 'NE',
  nginx: 'NG',
  npm: 'NP',
  nuxt: 'NU',
  nytimes: 'NY',
  okta: 'OK',
  openstreetmap: 'OP',
  oracle: 'OR',
  origin: 'OR',
  overleaf: 'OV',
  paddle: 'PA',
  pandora: 'PA',
  patreoncreators: 'PA',
  payoneer: 'PA',
  paytm: 'PA',
  peacock: 'PE',
  pipedrive: 'PI',
  pixabay: 'PI',
  pixiv: 'PI',
  pluralsight: 'PL',
  pocketcasts: 'PO',
  prettier: 'PR',
  producthunt: 'PR',
  pusher: 'PU',
  pytorch: 'PY',
  quora: 'QU',
  rabbitmq: 'RA',
  react: 'RE',
  readthedocs: 'RE',
  replit: 'RE',
  resend: 'RE',
  rollbar: 'RO',
  rss: 'RS',
  salesforce: 'SA',
  sanity: 'SA',
  scaleway: 'SC',
  scribd: 'SC',
  segment: 'SE',
  sentry: 'SE',
  signal: 'SI',
  sketch: 'SK',
  slack: 'SL',
  slideshare: 'SL',
  snapcraft: 'SN',
  sourceforge: 'SO',
  speedtest: 'SP',
  square: 'SQ',
  stabilityai: 'ST',
  stackshare: 'ST',
  statista: 'ST',
  storybook: 'ST',
  strapi: 'ST',
  substack: 'SU',
  surge: 'SU',
  symfony: 'SY',
  taiga: 'TA',
  taobao: 'TA',
  terraform: 'TE',
  theguardian: 'TH',
  tidal: 'TI',
  toptal: 'TO',
  tutanota: 'TU',
  typeform: 'TY',
  unsplash: 'UN',
  upstash: 'UP',
  uptime: 'UP',
  wikimedia: 'WI',
  xing: 'XI',
  yahoofinance: 'YA',
  yandex: 'YA',
  yelp: 'YE',
  zendesk: 'ZE',
  zerodha: 'ZE',
  zillow: 'ZI',
  zulip: 'ZU',
};

// Mapa de iconos SVG disponibles por servicio.
// Si un servicio no aparece aquÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â­, la UI usa glifo textual de `SERVICE_ICON_GLYPHS`.
export const SERVICE_ICON_ASSETS: Record<string, string> = {
  steam: 'assets/icons/services/steam.svg',
  steamcommunity: 'assets/icons/services/steamcommunity.svg',
  github: 'assets/icons/services/github.svg',
  gitlab: 'assets/icons/services/gitlab.svg',
  google: 'assets/icons/services/google.svg',
  gmail: 'assets/icons/services/gmail.svg',
  youtube: 'assets/icons/services/youtube.svg',
  vimeo: 'assets/icons/services/vimeo.svg',
  discord: 'assets/icons/services/discord.svg',
  reddit: 'assets/icons/services/reddit.svg',
  stackoverflow: 'assets/icons/services/stackoverflow.svg',
  wikipedia: 'assets/icons/services/wikipedia.svg',
  imgur: 'assets/icons/services/imgur.svg',
  twitch: 'assets/icons/services/twitch.svg',
  paypal: 'assets/icons/services/paypal.svg',
  binance: 'assets/icons/services/binance.svg',
  twitterx: 'assets/icons/services/twitterx.svg',
  tumblr: 'assets/icons/services/tumblr.svg',
  facebook: 'assets/icons/services/facebook.svg',
  messenger: 'assets/icons/services/messenger.svg',
  instagram: 'assets/icons/services/instagram.svg',
  linkedin: 'assets/icons/services/linkedin.svg',
  windows: 'assets/icons/services/windows.svg',
  visualstudio: 'assets/icons/services/visualstudio.svg',
  visualstudiocode: 'assets/icons/services/visualstudiocode.svg',
  dropbox: 'assets/icons/services/dropbox.svg',
  wetransfer: 'assets/icons/services/wetransfer.svg',
  mega: 'assets/icons/services/mega.svg',
  notion: 'assets/icons/services/notion.svg',
  openai: 'assets/icons/services/openai.svg',
  riotgames: 'assets/icons/services/riotgames.svg',
  epicgames: 'assets/icons/services/epicgames.svg',
  ubisoft: 'assets/icons/services/ubisoft.svg',
  uber: 'assets/icons/services/uber.svg',
  udemy: 'assets/icons/services/udemy.svg',
  ea: 'assets/icons/services/ea.svg',
  spotify: 'assets/icons/services/spotify.svg',
  soundcloud: 'assets/icons/services/soundcloud.svg',
  strava: 'assets/icons/services/strava.svg',
  netflix: 'assets/icons/services/netflix.svg',
  crunchyroll: 'assets/icons/services/crunchyroll.svg',
  apple: 'assets/icons/services/apple.svg',
  icloud: 'assets/icons/services/icloud.svg',
  jira: 'assets/icons/services/jira.svg',
  confluence: 'assets/icons/services/confluence.svg',
  trello: 'assets/icons/services/trello.svg',
  bitbucket: 'assets/icons/services/bitbucket.svg',
  gitkraken: 'assets/icons/services/gitkraken.svg',
  atlassian: 'assets/icons/services/atlassian.svg',
  figma: 'assets/icons/services/figma.svg',
  zoom: 'assets/icons/services/zoom.svg',
  loom: 'assets/icons/services/loom.svg',
  nasa: 'assets/icons/services/nasa.svg',
  telegram: 'assets/icons/services/telegram.svg',
  wechat: 'assets/icons/services/wechat.svg',
  weibo: 'assets/icons/services/weibo.svg',
  tencent: 'assets/icons/services/tencent.png',
  whatsapp: 'assets/icons/services/whatsapp.svg',
  protonmail: 'assets/icons/services/protonmail.svg',
  postman: 'assets/icons/services/postman.svg',
  tiktok: 'assets/icons/services/tiktok.svg',
  tinder: 'assets/icons/services/tinder.svg',
  pinterest: 'assets/icons/services/pinterest.svg',
  onlyfans: 'assets/icons/services/onlyfans.svg',
  roblox: 'assets/icons/services/roblox.svg',
  battlenet: 'assets/icons/services/battlenet.svg',
  playstation: 'assets/icons/services/playstation.svg',
  playstore: 'assets/icons/services/playstore.svg',
  docker: 'assets/icons/services/docker.svg',
  php: 'assets/icons/services/php.svg',
  redhat: 'assets/icons/services/redhat.svg',
  chrome: 'assets/icons/services/chrome.svg',
  firefox: 'assets/icons/services/firefox.svg',
  opera: 'assets/icons/services/opera.svg',
  brave: 'assets/icons/services/brave.svg',
  onepassword: 'assets/icons/services/onepassword.svg',
  lastpass: 'assets/icons/services/lastpass.svg',
  bitwarden: 'assets/icons/services/bitwarden.svg',
  coinbase: 'assets/icons/services/coinbase.svg',
  coinmarketcap: 'assets/icons/services/coinmarketcap.svg',
  stripe: 'assets/icons/services/stripe.svg',
  tripadvisor: 'assets/icons/services/tripadvisor.svg',
  shopify: 'assets/icons/services/shopify.svg',
  patreon: 'assets/icons/services/patreon.svg',
  evernote: 'assets/icons/services/evernote.svg',
  obsidian: 'assets/icons/services/obsidian.svg',
  linear: 'assets/icons/services/linear.svg',
  vercel: 'assets/icons/services/vercel.svg',
  webflow: 'assets/icons/services/webflow.svg',
  webpack: 'assets/icons/services/webpack.svg',
  wordpress: 'assets/icons/services/wordpress.svg',
  netlify: 'assets/icons/services/netlify.svg',
  snapchat: 'assets/icons/services/snapchat.svg',
  adobe: 'assets/icons/services/adobe.svg',
  sendgrid: 'assets/icons/services/sendgrid.svg',
  twilio: 'assets/icons/services/twilio.svg',
  cloudflare: 'assets/icons/services/cloudflare.svg',
  virustotal: 'assets/icons/services/virustotal.svg',
  digitalocean: 'assets/icons/services/digitalocean.svg',
  vultr: 'assets/icons/services/vultr.svg',
  railway: 'assets/icons/services/railway.svg',
  render: 'assets/icons/services/render.svg',
  supabase: 'assets/icons/services/supabase.svg',
  firebase: 'assets/icons/services/firebase.svg',
  w3schools: 'assets/icons/services/w3schools.svg',
  planetscale: 'assets/icons/services/planetscale.svg',
  mongodb: 'assets/icons/services/mongodb.svg',
  mysql: 'assets/icons/services/mysql.svg',
  postgresql: 'assets/icons/services/postgresql.svg',
  nvidia: 'assets/icons/services/nvidia.svg',
  rockstar: 'assets/icons/services/rockstar.svg',
  valorant: 'assets/icons/services/valorant.svg',
  kraken: 'assets/icons/services/kraken.svg',
  etoro: 'assets/icons/services/etoro.svg',
  tradingview: 'assets/icons/services/tradingview.svg',
  bbva: 'assets/icons/services/bbva.svg',
  santander: 'assets/icons/services/santander.svg',
  caixabank: 'assets/icons/services/caixabank.svg',
  revolut: 'assets/icons/services/revolut.svg',
  wise: 'assets/icons/services/wise.svg',
  hbo: 'assets/icons/services/hbo.svg',
  hbomax: 'assets/icons/services/hbomax.svg',
  paramountplus: 'assets/icons/services/paramountplus.svg',
  appletv: 'assets/icons/services/appletv.svg',
  proton: 'assets/icons/services/proton.svg',
  zoho: 'assets/icons/services/zoho.svg',
  googledrive: 'assets/icons/services/googledrive.svg',
  box: 'assets/icons/services/box.svg',
  anthropic: 'assets/icons/services/anthropic.svg',
  claude: 'assets/icons/services/claude.svg',
  perplexity: 'assets/icons/services/perplexity.svg',
  huggingface: 'assets/icons/services/huggingface.svg',
  replicate: 'assets/icons/services/replicate.svg',
  canva: 'assets/icons/services/canva.svg',
  asana: 'assets/icons/services/asana.svg',
  clickup: 'assets/icons/services/clickup.svg',
  todoist: 'assets/icons/services/todoist.svg',
  airtable: 'assets/icons/services/airtable.svg',
  adyen: 'assets/icons/services/adyen.svg',
  airbnb: 'assets/icons/services/airbnb.svg',
  algolia: 'assets/icons/services/algolia.svg',
  aliexpress: 'assets/icons/services/aliexpress.svg',
  alipay: 'assets/icons/services/alipay.svg',
  amazon: 'assets/icons/services/amazon.svg',
  amplitude: 'assets/icons/services/amplitude.svg',
  android: 'assets/icons/services/android.svg',
  androidstudio: 'assets/icons/services/androidstudio.svg',
  angellist: 'assets/icons/services/angellist.svg',
  angular: 'assets/icons/services/angular.svg',
  apollo: 'assets/icons/services/apollo.svg',
  appstore: 'assets/icons/services/appstore.svg',
  asanabusiness: 'assets/icons/services/asanabusiness.svg',
  auth0: 'assets/icons/services/auth0.svg',
  autodesk: 'assets/icons/services/autodesk.svg',
  azure: 'assets/icons/services/azure.svg',
  basecamp: 'assets/icons/services/basecamp.svg',
  behance: 'assets/icons/services/behance.svg',
  bigcommerce: 'assets/icons/services/bigcommerce.svg',
  bing: 'assets/icons/services/bing.svg',
  bitly: 'assets/icons/services/bitly.svg',
  blender: 'assets/icons/services/blender.svg',
  bootstrap: 'assets/icons/services/bootstrap.svg',
  braintree: 'assets/icons/services/braintree.svg',
  bugsnag: 'assets/icons/services/bugsnag.svg',
  buzzfeed: 'assets/icons/services/buzzfeed.svg',
  cashapp: 'assets/icons/services/cashapp.svg',
  circleci: 'assets/icons/services/circleci.svg',
  clerk: 'assets/icons/services/clerk.svg',
  codecademy: 'assets/icons/services/codecademy.svg',
  codepen: 'assets/icons/services/codepen.svg',
  codesandbox: 'assets/icons/services/codesandbox.svg',
  coursera: 'assets/icons/services/coursera.svg',
  crunchbase: 'assets/icons/services/crunchbase.svg',
  dailymotion: 'assets/icons/services/dailymotion.svg',
  datadog: 'assets/icons/services/datadog.svg',
  deezer: 'assets/icons/services/deezer.svg',
  deliveroo: 'assets/icons/services/deliveroo.svg',
  deno: 'assets/icons/services/deno.svg',
  disneyplus: 'assets/icons/services/disneyplus.svg',
  disqus: 'assets/icons/services/disqus.svg',
  dockerhub: 'assets/icons/services/dockerhub.svg',
  dribbble: 'assets/icons/services/dribbble.svg',
  duckduckgo: 'assets/icons/services/duckduckgo.svg',
  ebay: 'assets/icons/services/ebay.svg',
  elastic: 'assets/icons/services/elastic.svg',
  elasticsearch: 'assets/icons/services/elasticsearch.svg',
  envato: 'assets/icons/services/envato.svg',
  etsy: 'assets/icons/services/etsy.svg',
  eventbrite: 'assets/icons/services/eventbrite.svg',
  expo: 'assets/icons/services/expo.svg',
  expressjs: 'assets/icons/services/expressjs.svg',
  fastly: 'assets/icons/services/fastly.svg',
  fastmail: 'assets/icons/services/fastmail.svg',
  feedly: 'assets/icons/services/feedly.svg',
  fiverr: 'assets/icons/services/fiverr.svg',
  flyio: 'assets/icons/services/flyio.svg',
  forgejo: 'assets/icons/services/forgejo.svg',
  formstack: 'assets/icons/services/formstack.svg',
  foursquare: 'assets/icons/services/foursquare.svg',
  framer: 'assets/icons/services/framer.svg',
  freshbooks: 'assets/icons/services/freshbooks.svg',
  frontapp: 'assets/icons/services/frontapp.svg',
  gatsby: 'assets/icons/services/gatsby.svg',
  genshin: 'assets/icons/services/genshin.svg',
  ghost: 'assets/icons/services/ghost.svg',
  giphy: 'assets/icons/services/giphy.svg',
  gitea: 'assets/icons/services/gitea.svg',
  godaddy: 'assets/icons/services/godaddy.svg',
  goodreads: 'assets/icons/services/goodreads.svg',
  grafana: 'assets/icons/services/grafana.svg',
  grammarly: 'assets/icons/services/grammarly.svg',
  gumroad: 'assets/icons/services/gumroad.svg',
  hackernews: 'assets/icons/services/hackernews.svg',
  hashnode: 'assets/icons/services/hashnode.svg',
  heroku: 'assets/icons/services/heroku.svg',
  homeassistant: 'assets/icons/services/homeassistant.svg',
  hotjar: 'assets/icons/services/hotjar.svg',
  hubspot: 'assets/icons/services/hubspot.svg',
  icloudmail: 'assets/icons/services/icloudmail.svg',
  ifttt: 'assets/icons/services/ifttt.svg',
  indeed: 'assets/icons/services/indeed.svg',
  invision: 'assets/icons/services/invision.svg',
  jetbrains: 'assets/icons/services/jetbrains.svg',
  joomla: 'assets/icons/services/joomla.svg',
  jsdelivr: 'assets/icons/services/jsdelivr.svg',
  kaggle: 'assets/icons/services/kaggle.svg',
  kakao: 'assets/icons/services/kakao.svg',
  kickstarter: 'assets/icons/services/kickstarter.svg',
  klarna: 'assets/icons/services/klarna.svg',
  koa: 'assets/icons/services/koa.svg',
  lastfm: 'assets/icons/services/lastfm.svg',
  leetcode: 'assets/icons/services/leetcode.svg',
  lemonsqueezy: 'assets/icons/services/lemonsqueezy.svg',
  letterboxd: 'assets/icons/services/letterboxd.svg',
  liberapay: 'assets/icons/services/liberapay.svg',
  linode: 'assets/icons/services/linode.svg',
  mailchimp: 'assets/icons/services/mailchimp.svg',
  mailgun: 'assets/icons/services/mailgun.svg',
  mapbox: 'assets/icons/services/mapbox.svg',
  mattermost: 'assets/icons/services/mattermost.svg',
  medium: 'assets/icons/services/medium.svg',
  miro: 'assets/icons/services/miro.svg',
  mixpanel: 'assets/icons/services/mixpanel.svg',
  monday: 'assets/icons/services/monday.svg',
  mozilla: 'assets/icons/services/mozilla.svg',
  namecheap: 'assets/icons/services/namecheap.svg',
  nextcloud: 'assets/icons/services/nextcloud.svg',
  nextjs: 'assets/icons/services/nextjs.svg',
  nginx: 'assets/icons/services/nginx.svg',
  npm: 'assets/icons/services/npm.svg',
  nuxt: 'assets/icons/services/nuxt.svg',
  nytimes: 'assets/icons/services/nytimes.svg',
  okta: 'assets/icons/services/okta.svg',
  openstreetmap: 'assets/icons/services/openstreetmap.svg',
  oracle: 'assets/icons/services/oracle.svg',
  origin: 'assets/icons/services/origin.svg',
  overleaf: 'assets/icons/services/overleaf.svg',
  paddle: 'assets/icons/services/paddle.svg',
  pandora: 'assets/icons/services/pandora.svg',
  patreoncreators: 'assets/icons/services/patreoncreators.svg',
  payoneer: 'assets/icons/services/payoneer.svg',
  paytm: 'assets/icons/services/paytm.svg',
  peacock: 'assets/icons/services/peacock.svg',
  pipedrive: 'assets/icons/services/pipedrive.svg',
  pixabay: 'assets/icons/services/pixabay.svg',
  pixiv: 'assets/icons/services/pixiv.svg',
  pluralsight: 'assets/icons/services/pluralsight.svg',
  pocketcasts: 'assets/icons/services/pocketcasts.svg',
  prettier: 'assets/icons/services/prettier.svg',
  producthunt: 'assets/icons/services/producthunt.svg',
  pusher: 'assets/icons/services/pusher.svg',
  pytorch: 'assets/icons/services/pytorch.svg',
  quora: 'assets/icons/services/quora.svg',
  rabbitmq: 'assets/icons/services/rabbitmq.svg',
  react: 'assets/icons/services/react.svg',
  readthedocs: 'assets/icons/services/readthedocs.svg',
  replit: 'assets/icons/services/replit.svg',
  resend: 'assets/icons/services/resend.svg',
  rollbar: 'assets/icons/services/rollbar.svg',
  rss: 'assets/icons/services/rss.svg',
  salesforce: 'assets/icons/services/salesforce.svg',
  sanity: 'assets/icons/services/sanity.svg',
  scaleway: 'assets/icons/services/scaleway.svg',
  scribd: 'assets/icons/services/scribd.svg',
  segment: 'assets/icons/services/segment.svg',
  sentry: 'assets/icons/services/sentry.svg',
  signal: 'assets/icons/services/signal.svg',
  sketch: 'assets/icons/services/sketch.svg',
  skype: 'assets/icons/services/skype.svg',
  slack: 'assets/icons/services/slack.svg',
  slideshare: 'assets/icons/services/slideshare.svg',
  snapcraft: 'assets/icons/services/snapcraft.svg',
  sourceforge: 'assets/icons/services/sourceforge.svg',
  speedtest: 'assets/icons/services/speedtest.svg',
  square: 'assets/icons/services/square.svg',
  stabilityai: 'assets/icons/services/stabilityai.svg',
  stackshare: 'assets/icons/services/stackshare.svg',
  statista: 'assets/icons/services/statista.svg',
  storybook: 'assets/icons/services/storybook.svg',
  strapi: 'assets/icons/services/strapi.svg',
  substack: 'assets/icons/services/substack.svg',
  surge: 'assets/icons/services/surge.svg',
  symfony: 'assets/icons/services/symfony.svg',
  taiga: 'assets/icons/services/taiga.svg',
  taobao: 'assets/icons/services/taobao.svg',
  terraform: 'assets/icons/services/terraform.svg',
  theguardian: 'assets/icons/services/theguardian.svg',
  tidal: 'assets/icons/services/tidal.svg',
  toptal: 'assets/icons/services/toptal.svg',
  tutanota: 'assets/icons/services/tutanota.svg',
  typeform: 'assets/icons/services/typeform.svg',
  unsplash: 'assets/icons/services/unsplash.svg',
  upstash: 'assets/icons/services/upstash.svg',
  uptime: 'assets/icons/services/uptime.svg',
  wikimedia: 'assets/icons/services/wikimedia.svg',
  xbox: 'assets/icons/services/xbox.svg',
  xing: 'assets/icons/services/xing.svg',
  yahoo: 'assets/icons/services/yahoo.svg',
  yahoofinance: 'assets/icons/services/yahoofinance.svg',
  yandex: 'assets/icons/services/yandex.svg',
  yelp: 'assets/icons/services/yelp.svg',
  zendesk: 'assets/icons/services/zendesk.svg',
  zerodha: 'assets/icons/services/zerodha.svg',
  zillow: 'assets/icons/services/zillow.svg',
  zulip: 'assets/icons/services/zulip.svg',
};

// Registro base para detecciÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â³n automÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¡tica de servicios.
// Ordenado por afinidad funcional para facilitar mantenimiento manual.
export const SERVICE_ICON_REGISTRY: ServiceDefinition[] = [
  { id: 'steam', displayName: 'Steam', iconName: 'steam', domains: ['steampowered.com'], keywords: ['steam'], aliases: [], priority: 80 },
  { id: 'steamcommunity', displayName: 'Steam Community', iconName: 'steamcommunity', domains: ['steamcommunity.com'], keywords: ['steamcommunity', 'steam community'], aliases: [], priority: 82 },
  { id: 'github', displayName: 'GitHub', iconName: 'github', domains: ['github.com'], keywords: ['github'], aliases: ['gh'], priority: 70 },
  { id: 'gitlab', displayName: 'GitLab', iconName: 'gitlab', domains: ['gitlab.com'], keywords: ['gitlab'], aliases: [], priority: 70 },
  { id: 'gmail', displayName: 'Gmail', iconName: 'gmail', domains: ['gmail.com', 'mail.google.com'], emailDomains: ['gmail.com'], keywords: ['gmail'], aliases: ['google mail'], priority: 92 },
  { id: 'google', displayName: 'Google', iconName: 'google', domains: ['google.com'], keywords: ['google'], aliases: [], priority: 75 },
  { id: 'youtube', displayName: 'YouTube', iconName: 'youtube', domains: ['youtube.com', 'youtu.be'], keywords: ['youtube'], aliases: ['yt'], priority: 75 },
  { id: 'vimeo', displayName: 'Vimeo', iconName: 'vimeo', domains: ['vimeo.com'], keywords: ['vimeo'], aliases: [], priority: 72 },
  { id: 'discord', displayName: 'Discord', iconName: 'discord', domains: ['discord.com', 'discord.gg'], keywords: ['discord'], aliases: [], priority: 70 },
  { id: 'reddit', displayName: 'Reddit', iconName: 'reddit', domains: ['reddit.com'], keywords: ['reddit'], aliases: ['subreddit'], priority: 70 },
  { id: 'stackoverflow', displayName: 'Stack Overflow', iconName: 'stackoverflow', domains: ['stackoverflow.com'], keywords: ['stackoverflow', 'stack overflow'], aliases: ['so'], priority: 74 },
  { id: 'wikipedia', displayName: 'Wikipedia', iconName: 'wikipedia', domains: ['wikipedia.org'], keywords: ['wikipedia'], aliases: [], priority: 74 },
  { id: 'imgur', displayName: 'Imgur', iconName: 'imgur', domains: ['imgur.com'], keywords: ['imgur'], aliases: [], priority: 70 },
  { id: 'twitch', displayName: 'Twitch', iconName: 'twitch', domains: ['twitch.tv'], keywords: ['twitch'], aliases: [], priority: 70 },
  {
    id: 'amazon',
    displayName: 'Amazon',
    iconName: 'amazon',
    domains: [
      'amazon.com',
      'amazon.es',
      'amazon.co.uk',
      'amazon.de',
      'amazon.fr',
      'amazon.it',
      'amazon.nl',
      'amazon.pl',
      'amazon.se',
      'amazon.ca',
      'amazon.com.mx',
      'amazon.com.br',
      'amazon.com.tr',
      'amazon.com.au',
      'amazon.co.jp',
      'amazon.in',
      'amazon.sg',
      'amazon.ae',
      'amazon.sa',
      'amazon.eg'
    ],
    keywords: ['amazon'],
    aliases: [],
    priority: 70
  },
  { id: 'paypal', displayName: 'PayPal', iconName: 'paypal', domains: ['paypal.com'], keywords: ['paypal'], aliases: [], priority: 70 },
  { id: 'binance', displayName: 'Binance', iconName: 'binance', domains: ['binance.com'], keywords: ['binance'], aliases: ['binance spot', 'binance futures'], priority: 80 },
  { id: 'twitterx', displayName: 'X / Twitter', iconName: 'twitterx', domains: ['twitter.com', 'x.com'], keywords: ['twitter'], aliases: ['tweetdeck'], priority: 70 },
  { id: 'tumblr', displayName: 'Tumblr', iconName: 'tumblr', domains: ['tumblr.com'], keywords: ['tumblr'], aliases: [], priority: 70 },
  { id: 'facebook', displayName: 'Facebook', iconName: 'facebook', domains: ['facebook.com', 'fb.com'], keywords: ['facebook'], aliases: ['fb'], priority: 70 },
  { id: 'messenger', displayName: 'Messenger', iconName: 'messenger', domains: ['messenger.com', 'm.me'], keywords: ['messenger'], aliases: ['facebook messenger'], priority: 74 },
  { id: 'instagram', displayName: 'Instagram', iconName: 'instagram', domains: ['instagram.com'], keywords: ['instagram'], aliases: ['insta'], priority: 70 },
  { id: 'linkedin', displayName: 'LinkedIn', iconName: 'linkedin', domains: ['linkedin.com'], keywords: ['linkedin'], aliases: ['linked in'], priority: 70 },
  { id: 'microsoft', displayName: 'Microsoft', iconName: 'microsoft', domains: ['microsoft.com'], keywords: ['microsoft'], aliases: ['ms'], priority: 68 },
  { id: 'windows', displayName: 'Windows', iconName: 'windows', domains: ['windows.com'], keywords: ['windows'], aliases: ['microsoft windows'], priority: 82 },
  { id: 'visualstudio', displayName: 'Visual Studio', iconName: 'visualstudio', domains: ['visualstudio.microsoft.com'], keywords: ['visualstudio', 'visual studio'], aliases: ['microsoft visual studio'], priority: 82 },
  { id: 'visualstudiocode', displayName: 'Visual Studio Code', iconName: 'visualstudiocode', domains: ['code.visualstudio.com'], keywords: ['visualstudiocode', 'visual studio code', 'vscode', 'vs code'], aliases: ['microsoft visual studio code'], priority: 86 },
  { id: 'outlook', displayName: 'Outlook', iconName: 'outlook', domains: ['outlook.com', 'live.com', 'hotmail.com'], emailDomains: ['outlook.com', 'live.com', 'hotmail.com'], keywords: ['outlook', 'hotmail'], aliases: ['microsoft mail'], priority: 88 },
  { id: 'dropbox', displayName: 'Dropbox', iconName: 'dropbox', domains: ['dropbox.com'], keywords: ['dropbox'], aliases: [], priority: 70 },
  { id: 'wetransfer', displayName: 'WeTransfer', iconName: 'wetransfer', domains: ['wetransfer.com'], keywords: ['wetransfer', 'we transfer'], aliases: [], priority: 70 },
  { id: 'mega', displayName: 'Mega', iconName: 'mega', domains: ['mega.nz'], keywords: ['mega'], aliases: [], priority: 68 },
  { id: 'notion', displayName: 'Notion', iconName: 'notion', domains: ['notion.so'], keywords: ['notion'], aliases: [], priority: 70 },
  { id: 'chatgpt', displayName: 'ChatGPT', iconName: 'openai', domains: ['chatgpt.com', 'chat.openai.com'], keywords: ['chatgpt'], aliases: ['chat gpt'], priority: 95 },
  { id: 'openai', displayName: 'OpenAI', iconName: 'openai', domains: ['openai.com'], keywords: ['openai'], aliases: [], priority: 80 },
  { id: 'riotgames', displayName: 'Riot Games', iconName: 'riotgames', domains: ['riotgames.com'], keywords: ['riotgames', 'riot games', 'riot'], aliases: ['valorant', 'league of legends'], priority: 75 },
  { id: 'epicgames', displayName: 'Epic Games', iconName: 'epicgames', domains: ['epicgames.com'], keywords: ['epic games'], aliases: ['epic'], priority: 72 },
  { id: 'ubisoft', displayName: 'Ubisoft', iconName: 'ubisoft', domains: ['ubisoft.com'], keywords: ['ubisoft'], aliases: ['uplay'], priority: 72 },
  { id: 'uber', displayName: 'Uber', iconName: 'uber', domains: ['uber.com'], keywords: ['uber'], aliases: [], priority: 72 },
  { id: 'udemy', displayName: 'Udemy', iconName: 'udemy', domains: ['udemy.com'], keywords: ['udemy'], aliases: [], priority: 72 },
  { id: 'ea', displayName: 'EA', iconName: 'ea', domains: ['ea.com'], keywords: ['electronic arts'], aliases: ['ea app', 'origin'], priority: 72 },
  { id: 'spotify', displayName: 'Spotify', iconName: 'spotify', domains: ['spotify.com'], keywords: ['spotify'], aliases: [], priority: 70 },
  { id: 'soundcloud', displayName: 'SoundCloud', iconName: 'soundcloud', domains: ['soundcloud.com'], keywords: ['soundcloud', 'sound cloud'], aliases: [], priority: 70 },
  { id: 'strava', displayName: 'Strava', iconName: 'strava', domains: ['strava.com'], keywords: ['strava'], aliases: [], priority: 70 },
  { id: 'netflix', displayName: 'Netflix', iconName: 'netflix', domains: ['netflix.com'], keywords: ['netflix'], aliases: [], priority: 70 },
  { id: 'disneyplus', displayName: 'Disney+', iconName: 'disneyplus', domains: ['disneyplus.com'], keywords: ['disney+'], aliases: ['disney plus'], priority: 72 },
  { id: 'primevideo', displayName: 'Prime Video', iconName: 'primevideo', domains: ['primevideo.com'], keywords: ['prime video'], aliases: ['amazon prime video'], priority: 74 },
  { id: 'crunchyroll', displayName: 'Crunchyroll', iconName: 'crunchyroll', domains: ['crunchyroll.com'], keywords: ['crunchyroll'], aliases: ['crunchy roll'], priority: 72 },
  { id: 'apple', displayName: 'Apple', iconName: 'apple', domains: ['apple.com'], keywords: ['apple'], aliases: ['apple id'], priority: 78 },
  { id: 'icloud', displayName: 'iCloud', iconName: 'icloud', domains: ['icloud.com'], keywords: ['icloud'], aliases: ['apple cloud'], priority: 86 },
  { id: 'jira', displayName: 'Jira', iconName: 'jira', domains: ['atlassian.net', 'jira.com'], keywords: ['jira'], aliases: ['jira cloud'], priority: 82 },
  { id: 'confluence', displayName: 'Confluence', iconName: 'confluence', domains: ['atlassian.net', 'confluence.atlassian.com'], keywords: ['confluence'], aliases: [], priority: 78 },
  { id: 'trello', displayName: 'Trello', iconName: 'trello', domains: ['trello.com'], keywords: ['trello'], aliases: [], priority: 76 },
  { id: 'bitbucket', displayName: 'Bitbucket', iconName: 'bitbucket', domains: ['bitbucket.org'], keywords: ['bitbucket'], aliases: [], priority: 76 },
  { id: 'gitkraken', displayName: 'GitKraken', iconName: 'gitkraken', domains: ['gitkraken.com'], keywords: ['gitkraken', 'git kraken'], aliases: [], priority: 78 },
  { id: 'atlassian', displayName: 'Atlassian', iconName: 'atlassian', domains: ['atlassian.com'], keywords: ['atlassian'], aliases: [], priority: 72 },
  { id: 'figma', displayName: 'Figma', iconName: 'figma', domains: ['figma.com'], keywords: ['figma'], aliases: [], priority: 75 },
  { id: 'zoom', displayName: 'Zoom', iconName: 'zoom', domains: ['zoom.us'], keywords: ['zoom'], aliases: ['zoom meetings'], priority: 75 },
  { id: 'loom', displayName: 'Loom', iconName: 'loom', domains: ['loom.com'], keywords: ['loom'], aliases: [], priority: 74 },
  { id: 'nasa', displayName: 'NASA', iconName: 'nasa', domains: ['nasa.gov'], keywords: ['nasa'], aliases: [], priority: 74 },
  { id: 'telegram', displayName: 'Telegram', iconName: 'telegram', domains: ['telegram.org', 't.me'], keywords: ['telegram'], aliases: [], priority: 74 },
  { id: 'wechat', displayName: 'WeChat', iconName: 'wechat', domains: ['wechat.com', 'weixin.qq.com'], keywords: ['wechat', 'we chat'], aliases: ['weixin'], priority: 74 },
  { id: 'weibo', displayName: 'Weibo', iconName: 'weibo', domains: ['weibo.com'], keywords: ['weibo'], aliases: ['sina weibo'], priority: 74 },
  { id: 'tencent', displayName: 'Tencent', iconName: 'tencent', domains: ['tencent.com'], keywords: ['tencent'], aliases: [], priority: 72 },
  { id: 'whatsapp', displayName: 'WhatsApp', iconName: 'whatsapp', domains: ['whatsapp.com'], keywords: ['whatsapp'], aliases: [], priority: 74 },
  { id: 'protonmail', displayName: 'Proton Mail', iconName: 'protonmail', domains: ['proton.me', 'protonmail.com'], emailDomains: ['proton.me', 'protonmail.com'], keywords: ['proton mail', 'protonmail'], aliases: [], priority: 82 },
  { id: 'postman', displayName: 'Postman', iconName: 'postman', domains: ['postman.com'], keywords: ['postman'], aliases: ['postman api'], priority: 74 },
  { id: 'tiktok', displayName: 'TikTok', iconName: 'tiktok', domains: ['tiktok.com'], keywords: ['tiktok'], aliases: [], priority: 73 },
  { id: 'tinder', displayName: 'Tinder', iconName: 'tinder', domains: ['tinder.com'], keywords: ['tinder'], aliases: [], priority: 73 },
  { id: 'pinterest', displayName: 'Pinterest', iconName: 'pinterest', domains: ['pinterest.com'], keywords: ['pinterest'], aliases: [], priority: 73 },
  { id: 'onlyfans', displayName: 'OnlyFans', iconName: 'onlyfans', domains: ['onlyfans.com'], keywords: ['onlyfans', 'only fans'], aliases: [], priority: 73 },
  { id: 'roblox', displayName: 'Roblox', iconName: 'roblox', domains: ['roblox.com'], keywords: ['roblox'], aliases: [], priority: 72 },
  { id: 'battlenet', displayName: 'Battle.net', iconName: 'battlenet', domains: ['battle.net', 'blizzard.com'], keywords: ['battle.net'], aliases: ['battlenet', 'blizzard'], priority: 80 },
  { id: 'playstation', displayName: 'PlayStation', iconName: 'playstation', domains: ['playstation.com'], keywords: ['playstation'], aliases: ['psn'], priority: 74 },
  { id: 'playstore', displayName: 'Google Play Store', iconName: 'playstore', domains: ['play.google.com'], keywords: ['playstore', 'play store', 'google play'], aliases: ['google play store'], priority: 74 },
  { id: 'docker', displayName: 'Docker', iconName: 'docker', domains: ['docker.com', 'hub.docker.com'], keywords: ['docker'], aliases: ['docker hub'], priority: 74 },
  { id: 'php', displayName: 'PHP', iconName: 'php', domains: ['php.net'], keywords: ['php'], aliases: [], priority: 70 },
  { id: 'redhat', displayName: 'Red Hat', iconName: 'redhat', domains: ['redhat.com'], keywords: ['redhat', 'red hat', 'rhel'], aliases: ['red hat enterprise linux'], priority: 72 },
  { id: 'chrome', displayName: 'Google Chrome', iconName: 'chrome', domains: ['chrome.google.com'], keywords: ['chrome'], aliases: ['google chrome'], priority: 70 },
  { id: 'firefox', displayName: 'Firefox', iconName: 'firefox', domains: ['firefox.com', 'mozilla.org'], keywords: ['firefox'], aliases: ['mozilla firefox'], priority: 70 },
  { id: 'opera', displayName: 'Opera', iconName: 'opera', domains: ['opera.com'], keywords: ['opera'], aliases: ['opera gx'], priority: 70 },
  { id: 'brave', displayName: 'Brave', iconName: 'brave', domains: ['brave.com'], keywords: ['brave'], aliases: ['brave browser'], priority: 70 },
  { id: 'onepassword', displayName: '1Password', iconName: 'onepassword', domains: ['1password.com'], keywords: ['1password'], aliases: ['onepassword'], priority: 74 },
  { id: 'lastpass', displayName: 'LastPass', iconName: 'lastpass', domains: ['lastpass.com'], keywords: ['lastpass'], aliases: [], priority: 72 },
  { id: 'bitwarden', displayName: 'Bitwarden', iconName: 'bitwarden', domains: ['bitwarden.com'], keywords: ['bitwarden'], aliases: [], priority: 72 },
  { id: 'coinbase', displayName: 'Coinbase', iconName: 'coinbase', domains: ['coinbase.com'], keywords: ['coinbase'], aliases: [], priority: 74 },
  { id: 'coinmarketcap', displayName: 'CoinMarketCap', iconName: 'coinmarketcap', domains: ['coinmarketcap.com'], keywords: ['coinmarketcap', 'coin market cap'], aliases: ['cmc'], priority: 74 },
  { id: 'stripe', displayName: 'Stripe', iconName: 'stripe', domains: ['stripe.com'], keywords: ['stripe'], aliases: [], priority: 72 },
  { id: 'tripadvisor', displayName: 'Tripadvisor', iconName: 'tripadvisor', domains: ['tripadvisor.com'], keywords: ['tripadvisor', 'trip advisor'], aliases: [], priority: 72 },
  { id: 'shopify', displayName: 'Shopify', iconName: 'shopify', domains: ['shopify.com', 'myshopify.com'], keywords: ['shopify'], aliases: [], priority: 72 },
  { id: 'patreon', displayName: 'Patreon', iconName: 'patreon', domains: ['patreon.com'], keywords: ['patreon'], aliases: [], priority: 72 },
  { id: 'evernote', displayName: 'Evernote', iconName: 'evernote', domains: ['evernote.com'], keywords: ['evernote'], aliases: [], priority: 70 },
  { id: 'obsidian', displayName: 'Obsidian', iconName: 'obsidian', domains: ['obsidian.md'], keywords: ['obsidian'], aliases: [], priority: 70 },
  { id: 'linear', displayName: 'Linear', iconName: 'linear', domains: ['linear.app'], keywords: ['linear'], aliases: [], priority: 70 },
  { id: 'vercel', displayName: 'Vercel', iconName: 'vercel', domains: ['vercel.com'], keywords: ['vercel'], aliases: [], priority: 70 },
  { id: 'webflow', displayName: 'Webflow', iconName: 'webflow', domains: ['webflow.com'], keywords: ['webflow'], aliases: [], priority: 70 },
  { id: 'webpack', displayName: 'Webpack', iconName: 'webpack', domains: ['webpack.js.org'], keywords: ['webpack'], aliases: [], priority: 70 },
  { id: 'wordpress', displayName: 'WordPress', iconName: 'wordpress', domains: ['wordpress.com', 'wordpress.org'], keywords: ['wordpress', 'word press'], aliases: ['wp'], priority: 72 },
  { id: 'netlify', displayName: 'Netlify', iconName: 'netlify', domains: ['netlify.com'], keywords: ['netlify'], aliases: [], priority: 70 },
  { id: 'snapchat', displayName: 'Snapchat', iconName: 'snapchat', domains: ['snapchat.com'], keywords: ['snapchat'], aliases: [], priority: 70 },
  { id: 'skype', displayName: 'Skype', iconName: 'skype', domains: ['skype.com'], keywords: ['skype'], aliases: [], priority: 70 },
  { id: 'teams', displayName: 'Microsoft Teams', iconName: 'teams', domains: ['teams.microsoft.com'], keywords: ['teams', 'microsoft teams'], aliases: [], priority: 76 },
  { id: 'adobe', displayName: 'Adobe', iconName: 'adobe', domains: ['adobe.com'], keywords: ['adobe'], aliases: ['creative cloud'], priority: 70 },
  { id: 'twilio', displayName: 'Twilio', iconName: 'twilio', domains: ['twilio.com'], keywords: ['twilio'], aliases: [], priority: 72 },
  { id: 'sendgrid', displayName: 'SendGrid', iconName: 'sendgrid', domains: ['sendgrid.com'], keywords: ['sendgrid', 'send grid'], aliases: ['twilio sendgrid'], priority: 72 },
  { id: 'yahoo', displayName: 'Yahoo', iconName: 'yahoo', domains: ['yahoo.com'], keywords: ['yahoo'], aliases: [], priority: 68 },
  { id: 'yahoomail', displayName: 'Yahoo Mail', iconName: 'yahoomail', domains: ['mail.yahoo.com'], emailDomains: ['yahoo.com', 'yahoo.es', 'ymail.com'], keywords: ['yahoo mail'], aliases: ['ymail'], priority: 84 },
  { id: 'aws', displayName: 'AWS', iconName: 'aws', domains: ['amazonaws.com', 'aws.amazon.com'], keywords: ['aws', 'amazon web services'], aliases: [], priority: 74 },
  { id: 'cloudflare', displayName: 'Cloudflare', iconName: 'cloudflare', domains: ['cloudflare.com'], keywords: ['cloudflare'], aliases: [], priority: 74 },
  { id: 'virustotal', displayName: 'VirusTotal', iconName: 'virustotal', domains: ['virustotal.com'], keywords: ['virustotal', 'virus total'], aliases: [], priority: 74 },
  { id: 'digitalocean', displayName: 'DigitalOcean', iconName: 'digitalocean', domains: ['digitalocean.com'], keywords: ['digitalocean'], aliases: ['do'], priority: 72 },
  { id: 'vultr', displayName: 'Vultr', iconName: 'vultr', domains: ['vultr.com'], keywords: ['vultr'], aliases: [], priority: 72 },
  { id: 'heroku', displayName: 'Heroku', iconName: 'heroku', domains: ['heroku.com'], keywords: ['heroku'], aliases: [], priority: 70 },
  { id: 'railway', displayName: 'Railway', iconName: 'railway', domains: ['railway.app'], keywords: ['railway'], aliases: [], priority: 70 },
  { id: 'render', displayName: 'Render', iconName: 'render', domains: ['render.com'], keywords: ['render'], aliases: [], priority: 70 },
  { id: 'supabase', displayName: 'Supabase', iconName: 'supabase', domains: ['supabase.com'], keywords: ['supabase'], aliases: [], priority: 72 },
  { id: 'firebase', displayName: 'Firebase', iconName: 'firebase', domains: ['firebase.google.com'], keywords: ['firebase'], aliases: [], priority: 72 },
  { id: 'w3schools', displayName: 'W3Schools', iconName: 'w3schools', domains: ['w3schools.com'], keywords: ['w3schools', 'w3school'], aliases: ['w3 schools'], priority: 70 },
  { id: 'planetscale', displayName: 'PlanetScale', iconName: 'planetscale', domains: ['planetscale.com'], keywords: ['planetscale'], aliases: [], priority: 70 },
  { id: 'mongodb', displayName: 'MongoDB', iconName: 'mongodb', domains: ['mongodb.com'], keywords: ['mongodb', 'mongo'], aliases: [], priority: 72 },
  { id: 'mysql', displayName: 'MySQL', iconName: 'mysql', domains: ['mysql.com'], keywords: ['mysql', 'my sql'], aliases: [], priority: 70 },
  { id: 'postgresql', displayName: 'PostgreSQL', iconName: 'postgresql', domains: ['postgresql.org'], keywords: ['postgresql', 'postgres'], aliases: [], priority: 70 },
  { id: 'xbox', displayName: 'Xbox', iconName: 'xbox', domains: ['xbox.com'], keywords: ['xbox'], aliases: ['xbox live'], priority: 72 },
  { id: 'nintendo', displayName: 'Nintendo', iconName: 'nintendo', domains: ['nintendo.com'], keywords: ['nintendo'], aliases: [], priority: 70 },
  { id: 'nvidia', displayName: 'NVIDIA', iconName: 'nvidia', domains: ['nvidia.com'], keywords: ['nvidia'], aliases: [], priority: 74 },
  { id: 'rockstar', displayName: 'Rockstar Games', iconName: 'rockstar', domains: ['rockstargames.com'], keywords: ['rockstar', 'rockstar games'], aliases: ['gta online'], priority: 74 },
  { id: 'genshin', displayName: 'Genshin Impact', iconName: 'genshin', domains: ['hoyoverse.com', 'mihoyo.com'], keywords: ['genshin', 'genshin impact'], aliases: ['hoyoverse'], priority: 72 },
  { id: 'minecraft', displayName: 'Minecraft', iconName: 'minecraft', domains: ['minecraft.net'], keywords: ['minecraft'], aliases: [], priority: 72 },
  { id: 'valorant', displayName: 'Valorant', iconName: 'valorant', domains: ['playvalorant.com'], keywords: ['valorant'], aliases: [], priority: 74 },
  { id: 'kraken', displayName: 'Kraken', iconName: 'kraken', domains: ['kraken.com'], keywords: ['kraken'], aliases: [], priority: 74 },
  { id: 'etoro', displayName: 'eToro', iconName: 'etoro', domains: ['etoro.com'], keywords: ['etoro', 'e toro'], aliases: [], priority: 74 },
  { id: 'tradingview', displayName: 'TradingView', iconName: 'tradingview', domains: ['tradingview.com'], keywords: ['tradingview', 'trading view'], aliases: ['tv charts'], priority: 74 },
  { id: 'bbva', displayName: 'BBVA', iconName: 'bbva', domains: ['bbva.com', 'bbva.es'], keywords: ['bbva'], aliases: ['bbva net cash'], priority: 86 },
  { id: 'santander', displayName: 'Santander', iconName: 'santander', domains: ['santander.com', 'bancosantander.es'], keywords: ['santander'], aliases: ['santander consumer'], priority: 86 },
  { id: 'caixabank', displayName: 'CaixaBank', iconName: 'caixabank', domains: ['caixabank.es', 'imagin.com'], keywords: ['caixabank', 'la caixa', 'imagin'], aliases: ['caixa'], priority: 86 },
  { id: 'bankinter', displayName: 'Bankinter', iconName: 'bankinter', domains: ['bankinter.com', 'bankinter.es'], keywords: ['bankinter'], aliases: [], priority: 84 },
  { id: 'laboralkutxa', displayName: 'Laboral Kutxa', iconName: 'laboralkutxa', domains: ['laboralkutxa.com', 'cajalaboral.com'], keywords: ['laboral kutxa', 'caja laboral'], aliases: ['kutxa laboral'], priority: 84 },
  { id: 'sabadell', displayName: 'Banco Sabadell', iconName: 'sabadell', domains: ['bancsabadell.com', 'sabadellatlantico.com'], keywords: ['sabadell', 'banco sabadell'], aliases: [], priority: 84 },
  { id: 'abanca', displayName: 'ABANCA', iconName: 'abanca', domains: ['abanca.com'], keywords: ['abanca'], aliases: [], priority: 84 },
  { id: 'unicaja', displayName: 'Unicaja', iconName: 'unicaja', domains: ['unicajabanco.es'], keywords: ['unicaja'], aliases: [], priority: 84 },
  { id: 'openbank', displayName: 'Openbank', iconName: 'openbank', domains: ['openbank.es', 'openbank.com'], keywords: ['openbank'], aliases: [], priority: 84 },
  { id: 'kutxabank', displayName: 'Kutxabank', iconName: 'kutxabank', domains: ['kutxabank.es'], keywords: ['kutxabank'], aliases: ['kutxa bank'], priority: 84 },
  { id: 'ibercaja', displayName: 'Ibercaja', iconName: 'ibercaja', domains: ['ibercaja.es'], keywords: ['ibercaja'], aliases: [], priority: 84 },
  { id: 'ingbank', displayName: 'ING', iconName: 'ingbank', domains: ['ing.es', 'ing.com'], keywords: ['ing', 'ing bank'], aliases: ['ing direct'], priority: 84 },
  { id: 'metamask', displayName: 'MetaMask', iconName: 'metamask', domains: ['metamask.io'], keywords: ['metamask'], aliases: [], priority: 74 },
  { id: 'trustwallet', displayName: 'Trust Wallet', iconName: 'trustwallet', domains: ['trustwallet.com'], keywords: ['trust wallet'], aliases: ['trustwallet'], priority: 74 },
  { id: 'ledger', displayName: 'Ledger', iconName: 'ledger', domains: ['ledger.com'], keywords: ['ledger'], aliases: [], priority: 72 },
  { id: 'revolut', displayName: 'Revolut', iconName: 'revolut', domains: ['revolut.com'], keywords: ['revolut'], aliases: [], priority: 72 },
  { id: 'wise', displayName: 'Wise', iconName: 'wise', domains: ['wise.com'], keywords: ['wise'], aliases: ['transferwise'], priority: 72 },
  { id: 'hbo', displayName: 'HBO', iconName: 'hbo', domains: ['hbo.com'], keywords: ['hbo'], aliases: [], priority: 70 },
  { id: 'hbomax', displayName: 'HBO Max', iconName: 'hbomax', domains: ['hbomax.com', 'max.com'], keywords: ['hbo max'], aliases: ['max'], priority: 76 },
  { id: 'paramountplus', displayName: 'Paramount+', iconName: 'paramountplus', domains: ['paramountplus.com'], keywords: ['paramount+', 'paramount plus'], aliases: [], priority: 72 },
  { id: 'appletv', displayName: 'Apple TV', iconName: 'appletv', domains: ['tv.apple.com'], keywords: ['apple tv'], aliases: [], priority: 72 },
  { id: 'proton', displayName: 'Proton', iconName: 'proton', domains: ['proton.me'], keywords: ['proton'], aliases: [], priority: 72 },
  { id: 'zoho', displayName: 'Zoho', iconName: 'zoho', domains: ['zoho.com'], keywords: ['zoho'], aliases: [], priority: 70 },
  { id: 'fastmail', displayName: 'Fastmail', iconName: 'fastmail', domains: ['fastmail.com'], emailDomains: ['fastmail.com', 'fastmail.fm'], keywords: ['fastmail'], aliases: [], priority: 70 },
  { id: 'icloudmail', displayName: 'iCloud Mail', iconName: 'icloudmail', domains: ['icloud.com'], emailDomains: ['icloud.com', 'me.com', 'mac.com'], keywords: ['icloud mail', 'icloudmail'], aliases: ['icloudmail'], priority: 82 },
  { id: 'onedrive', displayName: 'OneDrive', iconName: 'onedrive', domains: ['onedrive.live.com'], keywords: ['onedrive'], aliases: ['one drive'], priority: 72 },
  { id: 'googledrive', displayName: 'Google Drive', iconName: 'googledrive', domains: ['drive.google.com'], keywords: ['google drive', 'drive'], aliases: ['gdrive', 'google drive'], priority: 88 },
  { id: 'box', displayName: 'Box', iconName: 'box', domains: ['box.com'], keywords: ['box'], aliases: ['box drive'], priority: 70 },
  { id: 'anthropic', displayName: 'Anthropic', iconName: 'anthropic', domains: ['anthropic.com'], keywords: ['anthropic'], aliases: [], priority: 74 },
  { id: 'claude', displayName: 'Claude', iconName: 'claude', domains: ['claude.ai'], keywords: ['claude'], aliases: [], priority: 80 },
  { id: 'perplexity', displayName: 'Perplexity', iconName: 'perplexity', domains: ['perplexity.ai'], keywords: ['perplexity'], aliases: [], priority: 74 },
  { id: 'midjourney', displayName: 'Midjourney', iconName: 'midjourney', domains: ['midjourney.com'], keywords: ['midjourney'], aliases: [], priority: 72 },
  { id: 'huggingface', displayName: 'Hugging Face', iconName: 'huggingface', domains: ['huggingface.co'], keywords: ['hugging face', 'huggingface'], aliases: ['hf'], priority: 74 },
  { id: 'replicate', displayName: 'Replicate', iconName: 'replicate', domains: ['replicate.com'], keywords: ['replicate'], aliases: [], priority: 72 },
  { id: 'canva', displayName: 'Canva', iconName: 'canva', domains: ['canva.com'], keywords: ['canva'], aliases: [], priority: 72 },
  { id: 'monday', displayName: 'monday.com', iconName: 'monday', domains: ['monday.com'], keywords: ['monday.com', 'monday'], aliases: [], priority: 70 },
  { id: 'asana', displayName: 'Asana', iconName: 'asana', domains: ['asana.com'], keywords: ['asana'], aliases: [], priority: 70 },
  { id: 'clickup', displayName: 'ClickUp', iconName: 'clickup', domains: ['clickup.com'], keywords: ['clickup'], aliases: ['click up'], priority: 72 },
  { id: 'todoist', displayName: 'Todoist', iconName: 'todoist', domains: ['todoist.com'], keywords: ['todoist'], aliases: [], priority: 70 },
  { id: 'airtable', displayName: 'Airtable', iconName: 'airtable', domains: ['airtable.com'], keywords: ['airtable'], aliases: [], priority: 70 },
  { id: 'adyen', displayName: 'Adyen', iconName: 'adyen', domains: [], keywords: ['adyen'], aliases: [], priority: 60 },
  { id: 'airbnb', displayName: 'Airbnb', iconName: 'airbnb', domains: [], keywords: ['airbnb'], aliases: [], priority: 60 },
  { id: 'algolia', displayName: 'Algolia', iconName: 'algolia', domains: [], keywords: ['algolia'], aliases: [], priority: 60 },
  { id: 'aliexpress', displayName: 'Aliexpress', iconName: 'aliexpress', domains: [], keywords: ['aliexpress'], aliases: [], priority: 60 },
  { id: 'alipay', displayName: 'Alipay', iconName: 'alipay', domains: [], keywords: ['alipay'], aliases: [], priority: 60 },
  { id: 'amplitude', displayName: 'Amplitude', iconName: 'amplitude', domains: [], keywords: ['amplitude'], aliases: [], priority: 60 },
  { id: 'android', displayName: 'Android', iconName: 'android', domains: [], keywords: ['android'], aliases: [], priority: 60 },
  { id: 'androidstudio', displayName: 'Android Studio', iconName: 'androidstudio', domains: [], keywords: ['androidstudio', 'android studio'], aliases: [], priority: 60 },
  { id: 'angellist', displayName: 'AngelList', iconName: 'angellist', domains: [], keywords: ['angellist'], aliases: [], priority: 60 },
  { id: 'angular', displayName: 'Angular', iconName: 'angular', domains: [], keywords: ['angular'], aliases: [], priority: 60 },
  { id: 'apollo', displayName: 'Apollo', iconName: 'apollo', domains: [], keywords: ['apollo'], aliases: [], priority: 60 },
  { id: 'appstore', displayName: 'App Store', iconName: 'appstore', domains: [], keywords: ['appstore', 'app store'], aliases: [], priority: 60 },
  { id: 'asanabusiness', displayName: 'Asana Business', iconName: 'asanabusiness', domains: [], keywords: ['asanabusiness', 'asana business'], aliases: [], priority: 60 },
  { id: 'auth0', displayName: 'Auth0', iconName: 'auth0', domains: [], keywords: ['auth0'], aliases: [], priority: 60 },
  { id: 'autodesk', displayName: 'Autodesk', iconName: 'autodesk', domains: [], keywords: ['autodesk'], aliases: [], priority: 60 },
  { id: 'azure', displayName: 'Azure', iconName: 'azure', domains: [], keywords: ['azure'], aliases: [], priority: 60 },
  { id: 'basecamp', displayName: 'Basecamp', iconName: 'basecamp', domains: [], keywords: ['basecamp'], aliases: [], priority: 60 },
  { id: 'behance', displayName: 'Behance', iconName: 'behance', domains: [], keywords: ['behance'], aliases: [], priority: 60 },
  { id: 'bigcommerce', displayName: 'BigCommerce', iconName: 'bigcommerce', domains: [], keywords: ['bigcommerce'], aliases: [], priority: 60 },
  { id: 'bing', displayName: 'Bing', iconName: 'bing', domains: [], keywords: ['bing'], aliases: [], priority: 60 },
  { id: 'bitly', displayName: 'Bitly', iconName: 'bitly', domains: [], keywords: ['bitly'], aliases: [], priority: 60 },
  { id: 'blender', displayName: 'Blender', iconName: 'blender', domains: [], keywords: ['blender'], aliases: [], priority: 60 },
  { id: 'bootstrap', displayName: 'Bootstrap', iconName: 'bootstrap', domains: [], keywords: ['bootstrap'], aliases: [], priority: 60 },
  { id: 'braintree', displayName: 'Braintree', iconName: 'braintree', domains: [], keywords: ['braintree'], aliases: [], priority: 60 },
  { id: 'bugsnag', displayName: 'Bugsnag', iconName: 'bugsnag', domains: [], keywords: ['bugsnag'], aliases: [], priority: 60 },
  { id: 'buzzfeed', displayName: 'Buzzfeed', iconName: 'buzzfeed', domains: [], keywords: ['buzzfeed'], aliases: [], priority: 60 },
  { id: 'cashapp', displayName: 'Cash App', iconName: 'cashapp', domains: [], keywords: ['cashapp', 'cash app'], aliases: [], priority: 60 },
  { id: 'circleci', displayName: 'CircleCI', iconName: 'circleci', domains: [], keywords: ['circleci'], aliases: [], priority: 60 },
  { id: 'clerk', displayName: 'Clerk', iconName: 'clerk', domains: [], keywords: ['clerk'], aliases: [], priority: 60 },
  { id: 'codecademy', displayName: 'Codecademy', iconName: 'codecademy', domains: [], keywords: ['codecademy'], aliases: [], priority: 60 },
  { id: 'codepen', displayName: 'CodePen', iconName: 'codepen', domains: [], keywords: ['codepen'], aliases: [], priority: 60 },
  { id: 'codesandbox', displayName: 'CodeSandbox', iconName: 'codesandbox', domains: [], keywords: ['codesandbox'], aliases: [], priority: 60 },
  { id: 'coursera', displayName: 'Coursera', iconName: 'coursera', domains: [], keywords: ['coursera'], aliases: [], priority: 60 },
  { id: 'crunchbase', displayName: 'Crunchbase', iconName: 'crunchbase', domains: [], keywords: ['crunchbase'], aliases: [], priority: 60 },
  { id: 'dailymotion', displayName: 'Dailymotion', iconName: 'dailymotion', domains: [], keywords: ['dailymotion'], aliases: [], priority: 60 },
  { id: 'datadog', displayName: 'Datadog', iconName: 'datadog', domains: [], keywords: ['datadog'], aliases: [], priority: 60 },
  { id: 'deezer', displayName: 'Deezer', iconName: 'deezer', domains: [], keywords: ['deezer'], aliases: [], priority: 60 },
  { id: 'deliveroo', displayName: 'Deliveroo', iconName: 'deliveroo', domains: [], keywords: ['deliveroo'], aliases: [], priority: 60 },
  { id: 'deno', displayName: 'Deno', iconName: 'deno', domains: [], keywords: ['deno'], aliases: [], priority: 60 },
  { id: 'disqus', displayName: 'Disqus', iconName: 'disqus', domains: [], keywords: ['disqus'], aliases: [], priority: 60 },
  { id: 'dockerhub', displayName: 'Docker Hub', iconName: 'dockerhub', domains: [], keywords: ['dockerhub', 'docker hub'], aliases: [], priority: 60 },
  { id: 'dribbble', displayName: 'Dribbble', iconName: 'dribbble', domains: [], keywords: ['dribbble'], aliases: [], priority: 60 },
  { id: 'duckduckgo', displayName: 'DuckDuckGo', iconName: 'duckduckgo', domains: [], keywords: ['duckduckgo'], aliases: [], priority: 60 },
  { id: 'ebay', displayName: 'Ebay', iconName: 'ebay', domains: [], keywords: ['ebay'], aliases: [], priority: 60 },
  { id: 'elastic', displayName: 'Elastic', iconName: 'elastic', domains: [], keywords: ['elastic'], aliases: [], priority: 60 },
  { id: 'elasticsearch', displayName: 'Elasticsearch', iconName: 'elasticsearch', domains: [], keywords: ['elasticsearch'], aliases: [], priority: 60 },
  { id: 'envato', displayName: 'Envato', iconName: 'envato', domains: [], keywords: ['envato'], aliases: [], priority: 60 },
  { id: 'etsy', displayName: 'Etsy', iconName: 'etsy', domains: [], keywords: ['etsy'], aliases: [], priority: 60 },
  { id: 'eventbrite', displayName: 'Eventbrite', iconName: 'eventbrite', domains: [], keywords: ['eventbrite'], aliases: [], priority: 60 },
  { id: 'expo', displayName: 'Expo', iconName: 'expo', domains: [], keywords: ['expo'], aliases: [], priority: 60 },
  { id: 'expressjs', displayName: 'Express.js', iconName: 'expressjs', domains: [], keywords: ['expressjs'], aliases: [], priority: 60 },
  { id: 'fastly', displayName: 'Fastly', iconName: 'fastly', domains: [], keywords: ['fastly'], aliases: [], priority: 60 },
  { id: 'feedly', displayName: 'Feedly', iconName: 'feedly', domains: [], keywords: ['feedly'], aliases: [], priority: 60 },
  { id: 'fiverr', displayName: 'Fiverr', iconName: 'fiverr', domains: [], keywords: ['fiverr'], aliases: [], priority: 60 },
  { id: 'flyio', displayName: 'Fly.io', iconName: 'flyio', domains: [], keywords: ['flyio'], aliases: [], priority: 60 },
  { id: 'forgejo', displayName: 'Forgejo', iconName: 'forgejo', domains: [], keywords: ['forgejo'], aliases: [], priority: 60 },
  { id: 'formstack', displayName: 'Formstack', iconName: 'formstack', domains: [], keywords: ['formstack'], aliases: [], priority: 60 },
  { id: 'foursquare', displayName: 'Foursquare', iconName: 'foursquare', domains: [], keywords: ['foursquare'], aliases: [], priority: 60 },
  { id: 'framer', displayName: 'Framer', iconName: 'framer', domains: [], keywords: ['framer'], aliases: [], priority: 60 },
  { id: 'freshbooks', displayName: 'FreshBooks', iconName: 'freshbooks', domains: [], keywords: ['freshbooks'], aliases: [], priority: 60 },
  { id: 'frontapp', displayName: 'Front', iconName: 'frontapp', domains: [], keywords: ['frontapp', 'front'], aliases: [], priority: 60 },
  { id: 'gatsby', displayName: 'Gatsby', iconName: 'gatsby', domains: [], keywords: ['gatsby'], aliases: [], priority: 60 },
  { id: 'ghost', displayName: 'Ghost', iconName: 'ghost', domains: [], keywords: ['ghost'], aliases: [], priority: 60 },
  { id: 'giphy', displayName: 'Giphy', iconName: 'giphy', domains: [], keywords: ['giphy'], aliases: [], priority: 60 },
  { id: 'gitea', displayName: 'Gitea', iconName: 'gitea', domains: [], keywords: ['gitea'], aliases: [], priority: 60 },
  { id: 'godaddy', displayName: 'GoDaddy', iconName: 'godaddy', domains: [], keywords: ['godaddy'], aliases: [], priority: 60 },
  { id: 'goodreads', displayName: 'Goodreads', iconName: 'goodreads', domains: [], keywords: ['goodreads'], aliases: [], priority: 60 },
  { id: 'grafana', displayName: 'Grafana', iconName: 'grafana', domains: [], keywords: ['grafana'], aliases: [], priority: 60 },
  { id: 'grammarly', displayName: 'Grammarly', iconName: 'grammarly', domains: [], keywords: ['grammarly'], aliases: [], priority: 60 },
  { id: 'gumroad', displayName: 'Gumroad', iconName: 'gumroad', domains: [], keywords: ['gumroad'], aliases: [], priority: 60 },
  { id: 'hackernews', displayName: 'Hacker News', iconName: 'hackernews', domains: [], keywords: ['hackernews', 'hacker news'], aliases: [], priority: 60 },
  { id: 'hashnode', displayName: 'Hashnode', iconName: 'hashnode', domains: [], keywords: ['hashnode'], aliases: [], priority: 60 },
  { id: 'homeassistant', displayName: 'Home Assistant', iconName: 'homeassistant', domains: [], keywords: ['homeassistant', 'home assistant'], aliases: [], priority: 60 },
  { id: 'hotjar', displayName: 'Hotjar', iconName: 'hotjar', domains: [], keywords: ['hotjar'], aliases: [], priority: 60 },
  { id: 'hubspot', displayName: 'HubSpot', iconName: 'hubspot', domains: [], keywords: ['hubspot'], aliases: [], priority: 60 },
  { id: 'ifttt', displayName: 'IFTTT', iconName: 'ifttt', domains: [], keywords: ['ifttt'], aliases: [], priority: 60 },
  { id: 'indeed', displayName: 'Indeed', iconName: 'indeed', domains: [], keywords: ['indeed'], aliases: [], priority: 60 },
  { id: 'invision', displayName: 'InVision', iconName: 'invision', domains: [], keywords: ['invision'], aliases: [], priority: 60 },
  { id: 'jetbrains', displayName: 'JetBrains', iconName: 'jetbrains', domains: [], keywords: ['jetbrains'], aliases: [], priority: 60 },
  { id: 'joomla', displayName: 'Joomla', iconName: 'joomla', domains: [], keywords: ['joomla'], aliases: [], priority: 60 },
  { id: 'jsdelivr', displayName: 'jsDelivr', iconName: 'jsdelivr', domains: [], keywords: ['jsdelivr'], aliases: [], priority: 60 },
  { id: 'kaggle', displayName: 'Kaggle', iconName: 'kaggle', domains: [], keywords: ['kaggle'], aliases: [], priority: 60 },
  { id: 'kakao', displayName: 'Kakao', iconName: 'kakao', domains: [], keywords: ['kakao'], aliases: [], priority: 60 },
  { id: 'kickstarter', displayName: 'Kickstarter', iconName: 'kickstarter', domains: [], keywords: ['kickstarter'], aliases: [], priority: 60 },
  { id: 'klarna', displayName: 'Klarna', iconName: 'klarna', domains: [], keywords: ['klarna'], aliases: [], priority: 60 },
  { id: 'koa', displayName: 'Koa', iconName: 'koa', domains: [], keywords: ['koa'], aliases: [], priority: 60 },
  { id: 'lastfm', displayName: 'Last.fm', iconName: 'lastfm', domains: [], keywords: ['lastfm'], aliases: [], priority: 60 },
  { id: 'leetcode', displayName: 'LeetCode', iconName: 'leetcode', domains: [], keywords: ['leetcode'], aliases: [], priority: 60 },
  { id: 'lemonsqueezy', displayName: 'Lemon Squeezy', iconName: 'lemonsqueezy', domains: [], keywords: ['lemonsqueezy', 'lemon squeezy'], aliases: [], priority: 60 },
  { id: 'letterboxd', displayName: 'Letterboxd', iconName: 'letterboxd', domains: [], keywords: ['letterboxd'], aliases: [], priority: 60 },
  { id: 'liberapay', displayName: 'Liberapay', iconName: 'liberapay', domains: [], keywords: ['liberapay'], aliases: [], priority: 60 },
  { id: 'linode', displayName: 'Linode', iconName: 'linode', domains: [], keywords: ['linode'], aliases: [], priority: 60 },
  { id: 'mailchimp', displayName: 'Mailchimp', iconName: 'mailchimp', domains: [], keywords: ['mailchimp'], aliases: [], priority: 60 },
  { id: 'mailgun', displayName: 'Mailgun', iconName: 'mailgun', domains: [], keywords: ['mailgun'], aliases: [], priority: 60 },
  { id: 'mapbox', displayName: 'Mapbox', iconName: 'mapbox', domains: [], keywords: ['mapbox'], aliases: [], priority: 60 },
  { id: 'mattermost', displayName: 'Mattermost', iconName: 'mattermost', domains: [], keywords: ['mattermost'], aliases: [], priority: 60 },
  { id: 'medium', displayName: 'Medium', iconName: 'medium', domains: [], keywords: ['medium'], aliases: [], priority: 60 },
  { id: 'miro', displayName: 'Miro', iconName: 'miro', domains: [], keywords: ['miro'], aliases: [], priority: 60 },
  { id: 'mixpanel', displayName: 'Mixpanel', iconName: 'mixpanel', domains: [], keywords: ['mixpanel'], aliases: [], priority: 60 },
  { id: 'mozilla', displayName: 'Mozilla', iconName: 'mozilla', domains: [], keywords: ['mozilla'], aliases: [], priority: 60 },
  { id: 'namecheap', displayName: 'Namecheap', iconName: 'namecheap', domains: [], keywords: ['namecheap'], aliases: [], priority: 60 },
  { id: 'nextcloud', displayName: 'Nextcloud', iconName: 'nextcloud', domains: [], keywords: ['nextcloud'], aliases: [], priority: 60 },
  { id: 'nextjs', displayName: 'Next.js', iconName: 'nextjs', domains: [], keywords: ['nextjs'], aliases: [], priority: 60 },
  { id: 'nginx', displayName: 'Nginx', iconName: 'nginx', domains: [], keywords: ['nginx'], aliases: [], priority: 60 },
  { id: 'npm', displayName: 'npm', iconName: 'npm', domains: [], keywords: ['npm'], aliases: [], priority: 60 },
  { id: 'nuxt', displayName: 'Nuxt', iconName: 'nuxt', domains: [], keywords: ['nuxt'], aliases: [], priority: 60 },
  { id: 'nytimes', displayName: 'The New York Times', iconName: 'nytimes', domains: [], keywords: ['nytimes', 'the new york times'], aliases: [], priority: 60 },
  { id: 'okta', displayName: 'Okta', iconName: 'okta', domains: [], keywords: ['okta'], aliases: [], priority: 60 },
  { id: 'openstreetmap', displayName: 'OpenStreetMap', iconName: 'openstreetmap', domains: [], keywords: ['openstreetmap'], aliases: [], priority: 60 },
  { id: 'oracle', displayName: 'Oracle', iconName: 'oracle', domains: [], keywords: ['oracle'], aliases: [], priority: 60 },
  { id: 'origin', displayName: 'Origin', iconName: 'origin', domains: [], keywords: ['origin'], aliases: [], priority: 60 },
  { id: 'overleaf', displayName: 'Overleaf', iconName: 'overleaf', domains: [], keywords: ['overleaf'], aliases: [], priority: 60 },
  { id: 'paddle', displayName: 'Paddle', iconName: 'paddle', domains: [], keywords: ['paddle'], aliases: [], priority: 60 },
  { id: 'pandora', displayName: 'Pandora', iconName: 'pandora', domains: [], keywords: ['pandora'], aliases: [], priority: 60 },
  { id: 'patreoncreators', displayName: 'Patreon Creators', iconName: 'patreoncreators', domains: [], keywords: ['patreoncreators', 'patreon creators'], aliases: [], priority: 60 },
  { id: 'payoneer', displayName: 'Payoneer', iconName: 'payoneer', domains: [], keywords: ['payoneer'], aliases: [], priority: 60 },
  { id: 'paytm', displayName: 'Paytm', iconName: 'paytm', domains: [], keywords: ['paytm'], aliases: [], priority: 60 },
  { id: 'peacock', displayName: 'Peacock', iconName: 'peacock', domains: [], keywords: ['peacock'], aliases: [], priority: 60 },
  { id: 'pipedrive', displayName: 'Pipedrive', iconName: 'pipedrive', domains: [], keywords: ['pipedrive'], aliases: [], priority: 60 },
  { id: 'pixabay', displayName: 'Pixabay', iconName: 'pixabay', domains: [], keywords: ['pixabay'], aliases: [], priority: 60 },
  { id: 'pixiv', displayName: 'Pixiv', iconName: 'pixiv', domains: [], keywords: ['pixiv'], aliases: [], priority: 60 },
  { id: 'pluralsight', displayName: 'Pluralsight', iconName: 'pluralsight', domains: [], keywords: ['pluralsight'], aliases: [], priority: 60 },
  { id: 'pocketcasts', displayName: 'Pocket Casts', iconName: 'pocketcasts', domains: [], keywords: ['pocketcasts', 'pocket casts'], aliases: [], priority: 60 },
  { id: 'prettier', displayName: 'Prettier', iconName: 'prettier', domains: [], keywords: ['prettier'], aliases: [], priority: 60 },
  { id: 'producthunt', displayName: 'Product Hunt', iconName: 'producthunt', domains: [], keywords: ['producthunt', 'product hunt'], aliases: [], priority: 60 },
  { id: 'pusher', displayName: 'Pusher', iconName: 'pusher', domains: [], keywords: ['pusher'], aliases: [], priority: 60 },
  { id: 'pytorch', displayName: 'PyTorch', iconName: 'pytorch', domains: [], keywords: ['pytorch'], aliases: [], priority: 60 },
  { id: 'quora', displayName: 'Quora', iconName: 'quora', domains: [], keywords: ['quora'], aliases: [], priority: 60 },
  { id: 'rabbitmq', displayName: 'RabbitMQ', iconName: 'rabbitmq', domains: [], keywords: ['rabbitmq'], aliases: [], priority: 60 },
  { id: 'react', displayName: 'React', iconName: 'react', domains: [], keywords: ['react'], aliases: [], priority: 60 },
  { id: 'readthedocs', displayName: 'Read the Docs', iconName: 'readthedocs', domains: [], keywords: ['readthedocs', 'read the docs'], aliases: [], priority: 60 },
  { id: 'replit', displayName: 'Replit', iconName: 'replit', domains: [], keywords: ['replit'], aliases: [], priority: 60 },
  { id: 'resend', displayName: 'Resend', iconName: 'resend', domains: [], keywords: ['resend'], aliases: [], priority: 60 },
  { id: 'rollbar', displayName: 'Rollbar', iconName: 'rollbar', domains: [], keywords: ['rollbar'], aliases: [], priority: 60 },
  { id: 'rss', displayName: 'RSS', iconName: 'rss', domains: [], keywords: ['rss'], aliases: [], priority: 60 },
  { id: 'salesforce', displayName: 'Salesforce', iconName: 'salesforce', domains: [], keywords: ['salesforce'], aliases: [], priority: 60 },
  { id: 'sanity', displayName: 'Sanity', iconName: 'sanity', domains: [], keywords: ['sanity'], aliases: [], priority: 60 },
  { id: 'scaleway', displayName: 'Scaleway', iconName: 'scaleway', domains: [], keywords: ['scaleway'], aliases: [], priority: 60 },
  { id: 'scribd', displayName: 'Scribd', iconName: 'scribd', domains: [], keywords: ['scribd'], aliases: [], priority: 60 },
  { id: 'segment', displayName: 'Segment', iconName: 'segment', domains: [], keywords: ['segment'], aliases: [], priority: 60 },
  { id: 'sentry', displayName: 'Sentry', iconName: 'sentry', domains: [], keywords: ['sentry'], aliases: [], priority: 60 },
  { id: 'signal', displayName: 'Signal', iconName: 'signal', domains: [], keywords: ['signal'], aliases: [], priority: 60 },
  { id: 'sketch', displayName: 'Sketch', iconName: 'sketch', domains: [], keywords: ['sketch'], aliases: [], priority: 60 },
  { id: 'slack', displayName: 'Slack', iconName: 'slack', domains: [], keywords: ['slack'], aliases: [], priority: 60 },
  { id: 'slideshare', displayName: 'SlideShare', iconName: 'slideshare', domains: [], keywords: ['slideshare'], aliases: [], priority: 60 },
  { id: 'snapcraft', displayName: 'Snapcraft', iconName: 'snapcraft', domains: [], keywords: ['snapcraft'], aliases: [], priority: 60 },
  { id: 'sourceforge', displayName: 'SourceForge', iconName: 'sourceforge', domains: [], keywords: ['sourceforge'], aliases: [], priority: 60 },
  { id: 'speedtest', displayName: 'Speedtest', iconName: 'speedtest', domains: [], keywords: ['speedtest'], aliases: [], priority: 60 },
  { id: 'square', displayName: 'Square', iconName: 'square', domains: [], keywords: ['square'], aliases: [], priority: 60 },
  { id: 'stabilityai', displayName: 'Stability AI', iconName: 'stabilityai', domains: [], keywords: ['stabilityai', 'stability ai'], aliases: [], priority: 60 },
  { id: 'stackshare', displayName: 'StackShare', iconName: 'stackshare', domains: [], keywords: ['stackshare'], aliases: [], priority: 60 },
  { id: 'statista', displayName: 'Statista', iconName: 'statista', domains: [], keywords: ['statista'], aliases: [], priority: 60 },
  { id: 'storybook', displayName: 'Storybook', iconName: 'storybook', domains: [], keywords: ['storybook'], aliases: [], priority: 60 },
  { id: 'strapi', displayName: 'Strapi', iconName: 'strapi', domains: [], keywords: ['strapi'], aliases: [], priority: 60 },
  { id: 'substack', displayName: 'Substack', iconName: 'substack', domains: [], keywords: ['substack'], aliases: [], priority: 60 },
  { id: 'surge', displayName: 'Surge', iconName: 'surge', domains: [], keywords: ['surge'], aliases: [], priority: 60 },
  { id: 'symfony', displayName: 'Symfony', iconName: 'symfony', domains: [], keywords: ['symfony'], aliases: [], priority: 60 },
  { id: 'taiga', displayName: 'Taiga', iconName: 'taiga', domains: [], keywords: ['taiga'], aliases: [], priority: 60 },
  { id: 'taobao', displayName: 'Taobao', iconName: 'taobao', domains: [], keywords: ['taobao'], aliases: [], priority: 60 },
  { id: 'terraform', displayName: 'Terraform', iconName: 'terraform', domains: [], keywords: ['terraform'], aliases: [], priority: 60 },
  { id: 'theguardian', displayName: 'The Guardian', iconName: 'theguardian', domains: [], keywords: ['theguardian', 'the guardian'], aliases: [], priority: 60 },
  { id: 'tidal', displayName: 'TIDAL', iconName: 'tidal', domains: [], keywords: ['tidal'], aliases: [], priority: 60 },
  { id: 'toptal', displayName: 'Toptal', iconName: 'toptal', domains: [], keywords: ['toptal'], aliases: [], priority: 60 },
  { id: 'tutanota', displayName: 'Tuta', iconName: 'tutanota', domains: [], keywords: ['tutanota', 'tuta'], aliases: [], priority: 60 },
  { id: 'typeform', displayName: 'Typeform', iconName: 'typeform', domains: [], keywords: ['typeform'], aliases: [], priority: 60 },
  { id: 'unsplash', displayName: 'Unsplash', iconName: 'unsplash', domains: [], keywords: ['unsplash'], aliases: [], priority: 60 },
  { id: 'upstash', displayName: 'Upstash', iconName: 'upstash', domains: [], keywords: ['upstash'], aliases: [], priority: 60 },
  { id: 'uptime', displayName: 'Uptime', iconName: 'uptime', domains: [], keywords: ['uptime'], aliases: [], priority: 60 },
  { id: 'wikimedia', displayName: 'Wikimedia', iconName: 'wikimedia', domains: [], keywords: ['wikimedia'], aliases: [], priority: 60 },
  { id: 'xing', displayName: 'XING', iconName: 'xing', domains: [], keywords: ['xing'], aliases: [], priority: 60 },
  { id: 'yahoofinance', displayName: 'Yahoo Finance', iconName: 'yahoofinance', domains: [], keywords: ['yahoofinance', 'yahoo finance'], aliases: [], priority: 60 },
  { id: 'yandex', displayName: 'Yandex', iconName: 'yandex', domains: [], keywords: ['yandex'], aliases: [], priority: 60 },
  { id: 'yelp', displayName: 'Yelp', iconName: 'yelp', domains: [], keywords: ['yelp'], aliases: [], priority: 60 },
  { id: 'zendesk', displayName: 'Zendesk', iconName: 'zendesk', domains: [], keywords: ['zendesk'], aliases: [], priority: 60 },
  { id: 'zerodha', displayName: 'Zerodha', iconName: 'zerodha', domains: [], keywords: ['zerodha'], aliases: [], priority: 60 },
  { id: 'zillow', displayName: 'Zillow', iconName: 'zillow', domains: [], keywords: ['zillow'], aliases: [], priority: 60 },
  { id: 'zulip', displayName: 'Zulip', iconName: 'zulip', domains: [], keywords: ['zulip'], aliases: [], priority: 60 },
];

